version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Atualize a linha abaixo apontando para a pasta src:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rag_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - grafanadata:/var/lib/grafana
    networks:
      - rag_network

volumes:
  pgdata:
  grafanadata:

networks:
  rag_network:
    driver: bridge