[project]
name = "mec-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.5.1",
    "onnxruntime>=1.27.0",
    "openai>=2.46.0",
    "pandas>=3.0.3",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sqlitesearch>=0.1.2",
    "tokenizers>=0.23.1",
    "tqdm>=4.69.0",
]

[dependency-groups]
dev = [
    "huggingface-hub>=1.24.0",
]
